name: gshock-time-server
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - pip:
     - -e .  # install git checkout of demo-dsproject in editable mode
     - pytz
     - bleak
     - reactivex

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark